apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: monorepo
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-46aafe08-6db7-430e-bed9-7b9d3690349f
      eventName: github-46aafe08-6db7-430e-bed9-7b9d3690349f
      eventSourceName: monorepo
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: express-folder
        conditions: github-46aafe08-6db7-430e-bed9-7b9d3690349f
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: monorepo-express-folder-
              spec:
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
