apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: monorepo
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-46aafe08-6db7-430e-bed9-7b9d3690349f:
      events:
        - push
      repositories:
        - owner: nightmar39
          names:
            - cd-five-mins
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/csdp-july/monorepo/github-46aafe08-6db7-430e-bed9-7b9d3690349f
        url: https://rozario-demo.sa.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
