apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: express
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-5f570c68-99c2-454f-b1ed-ea6b79c440fd
      eventName: github-5f570c68-99c2-454f-b1ed-ea6b79c440fd
      eventSourceName: express
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.head_commit.modified
            comparator: '='
            type: string
            value:
              - k8s-resources/*
  triggers:
    - template:
        name: trigger
        conditions: github-5f570c68-99c2-454f-b1ed-ea6b79c440fd
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: express-trigger-
              spec:
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
                arguments:
                  parameters:
                    - name: IMAGE
                      value: ''
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-5f570c68-99c2-454f-b1ed-ea6b79c440fd
                dataTemplate: placeholder
