apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: express
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-5f570c68-99c2-454f-b1ed-ea6b79c440fd:
      events:
        - push
      repositories:
        - owner: nightmar39
          names:
            - cd-five-mins
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/csdp-july/express/github-5f570c68-99c2-454f-b1ed-ea6b79c440fd
        url: https://rozario-demo.sa.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
